print ("")



print ("")
print ("")

#input
nama = input ("Ketikan Nama Anda            :   ")
nilai = ("Masukan Nilai Ujian Anda          :  ")

print ("")

a = input ("Masukan Nilai Ujian Anda     :  ")
print ("")
print ("")
nilai= int (a)
if ( nilai >=75):
    print ("Cetak               :  ")
    print ("Nama anda adalah    :  ",nama )
    print ("keterangan          : Lulus")
    
else :
    print ("cetak                   :")
    print ("Nama anda adalah        : ",nama )
    print ("keterangan              : Tidak Lulus")
